<?php

namespace Madmatt\EncryptAtRest\FieldType;

use SilverStripe\Core\Injector\Injector;
use SilverStripe\ORM\DB;
use SilverStripe\ORM\FieldType\DBDatetime;
use Madmatt\EncryptAtRest\AtRestCryptoService;

/**
 * Class EncryptedDatetime
 * @package EncryptAtRest\Fieldtypes
 *
 * This class wraps around a DBDatetime, storing the value in the database as an encrypted string in a varchar field, but
 * returning it to SilverStripe as a decrypted DBDatetime object.
 */
class EncryptedDatetime extends DBDatetime
{
    /**
     * @var AtRestCryptoService
     */
    protected $service;

    public function __construct($name = null, $options = [])
    {
        parent::__construct($name, $options);
        $this->service = Injector::inst()->get(AtRestCryptoService::class);
    }

    public function setValue($value, $record = null, $markChanged = true)
    {
        if (array_key_exists($this->name, $record) && $value === null) {
            $this->value = $record[$this->name];
        } else {
            $this->value = $value;
        }
    }

    public function getDecryptedValue($value)
    {
        // Test if we're actually an encrypted value;
        if (ctype_xdigit($value) && strlen($value) > 130) {
            return $this->service->decrypt($value);
        }
        return $value;
    }

    public function getValue()
    {
        return $this->getDecryptedValue($this->value); // TODO: Change the autogenerated stub
    }

    public function requireField()
    {
        $values = array(
            'type'  => 'text',
            'parts' => array(
                'datatype'   => 'text',
                'null'       => 'not null',
                'arrayValue' => $this->arrayValue
            )
        );

        DB::require_field($this->tableName, $this->name, $values);
    }

    public function prepValueForDB($value)
    {
        $value = parent::prepValueForDB($value);
        $ciphertext = $this->service->encrypt($value);
        $this->value = $ciphertext;
        return $ciphertext;
    }
}
